<?php 
require_once __DIR__ . '/layout/header.php';
?>

<main class="container mt-4">
    <form method="POST" action="add_video">
            <input type="text" name="titulo" placeholder="Título">
            <input type="text" name="autor" placeholder="Autor">
            <input name="descripcion" placeholder="Descripcion">
            <input type="number" name="duracion" placeholder="duracion">
            <input type="date" name="fecha_publicacion">
            <input type="text" name="url" placeholder="URL">
        <select name="id_categoria">
            <option value="1">Educación</option>
            <option value="2">Psicología</option>
        </select>
        <button type="submit">Guardar</button>
    </form>
</main>

<?php 
require_once __DIR__ . '/layout/footer.php';
?>