<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Issue Tracker</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="issues"><i class="bi bi-bug-fill"></i> Issue Tracker</a>
      <div class="navbar-nav me-auto">
        <a class="nav-link active" href="issues">Incidencias</a>
      </div>
      <div class="navbar-nav">
        <span class="navbar-text me-3"><i class="bi bi-person-circle"></i> <?php if($this->user): ?><?=$this->user->email?> <?php else: ?> <a href="login_form" >Login</a> <?php endif; ?></span>
        <a class="nav-link" href="login"><i class="bi bi-box-arrow-right"></i> Cerrar sesión</a>
      </div>
    </div>
  </nav>
