<?php 
require_once __DIR__ . '/layout/header.php';
?>

<main class="container mt-4">
    <form method="POST" action="<?= BASE_URL ?>actualizar_video/<?= $video->id_video ?>">
        <input name="titulo" value="<?= $video->titulo ?>">
        <input name="autor" value="<?= $video->autor ?>">
        <input name="descripcion" value="<?= $video->descripcion ?>">
        <input name="duracion" value="<?= $video->duracion ?>">
        <input type="date" name="fecha_publicacion" value="<?= $video->fecha_publicacion ?>">
        <input name="url" value="<?= $video->URL ?>">
        <select name="id_categoria">
            <option value="1" <?= $video->id_categoria == 1 ? 'selected' : '' ?>>Educación</option>
            <option value="2" <?= $video->id_categoria == 2 ? 'selected' : '' ?>>Psicología</option>
        </select>
        <button type="submit">Actualizar</button>
    </form>
</main>

<?php 
require_once __DIR__ . '/layout/footer.php';
?>