<?php 
require_once __DIR__ . '/layout/header.php';
?>

<main class="container mt-4">
    <h2>Agregar Categoría</h2>
    <form method="POST" action="<?= BASE_URL ?>add_categoria">
        <div class="mb-3">
            <label class="form-label">Nombre</label>
            <input
                type="text"
                name="nombre"
                class="form-control"
                required
            >
        </div>
        <button type="submit" class="btn btn-primary">
            Guardar
        </button>
    </form>

</main>

<?php 
require_once __DIR__ . '/layout/footer.php';
?>